# Tool Server Discovery
# List of MCP tool servers that the host should discover and use
tool_servers:
  - url: "http://localhost:5001"  # Product Server (MCP interface)
    path: "product-server/server_product.py"  # Path to the server script
  - url: "http://localhost:5002"  # Analytics Server (MCP interface)
    path: "analytics-server/server_analytics.py"  # Path to the server script

# Example: To add more tool servers in the future, just add their URLs:
#  - url: "http://localhost:5002"  # Analytics Server 
#    path: "analytics-server/server_analytics.py" 